### ISSUE TITLE
HMR does not work for Components

### ISSUE THREAD

**Issue by florianliebig** [lepikhinb/sugar#1]
When using npm run dev webserver alongside with php artisan serve or valet only Pages are correctly rebuilt and delivered to the browser via HMR.

**Expected behaviour (as per Pages)**

npm console shows

`11:37:36 PM [vite] hmr update /resources/js/Pages/Offer.vue
hmr update /resources/css/app.css (x2)
`

Browser console shows

`[vite] hot updated: /resources/js/Pages/Offer.vue
client.ts:348 [vite] hot updated: /resources/css/app.css`

**Behaviour when updating component**

`11:39:01 PM [vite] page reload resources/js/components/Breeze/ApplicationLogo.vue`

Nothing happens in the browser, not even after a hard page reload.

**Possible approach / Steps to reproduce**

I am using the default package app.ts

![2021-09-21 at 23 40](https://user-images.githubusercontent.com/10775702/134251524-2dc47f0f-c439-4058-a35d-8904e43f1003.jpg)

Only pages are imported in resolve property here.

I am using standard import in my Offer.vue Page:

```
<script setup lang="ts">
import { Head, Link } from '@inertiajs/inertia-vue3'
import { TrustBlock } from '@/Components/Subscription'
import { ApplicationLogo } from '@/Components/Breeze'
import ProductOverview from '@/Components/Subscription/ProductOverview.vue'

const props = defineProps({
    offer: Object as PropType<App.Models.Product>,
})
</script>


<template>
    <TrustBlock :heading="offer.name" :text="offer.description" />

    <ApplicationLogo />
...
```

Thanks in advance

**Comment by lepikhinb** [comment]
Can you check if it works as expected if you import the component directly?
```ts
import ApplicationLogo from '@/Components/Breeze/ApplicationLogo.vue'
```

**Comment by florianliebig** [comment]
Still the same issue @lepikhinb

**Comment by lepikhinb** [comment]
Ok, I’ll take a look tomorrow 🤷‍♂️

**Comment by florianliebig** [comment]
@lepikhinb After giving the whole thing a fresh start, incognito browser etc. some of the components work for HMR.. I will check in detail if there is something different on code basis and will come back when I can reproduce the issue clearly

**Comment by florianliebig** [comment]
Not able to reproduce this behavious. Thank you for this package :)
